---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/vigasin/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.ansible-downloads/dotfiles
dotfiles_files:
  - .gitconfig
  - .tmux.conf
  - .osx
  - .vimrc

homebrew_installed_packages:
  - amazon-ecs-cli
  - ansible
  - asciinema
  - automake
  - aview
  - awscli
  - awslogs
  - axel
  - bash-completion
  - bbe          # sed for binaries
  - binwalk
  - blackbox
  - bpm-tools
  - cfssl
  - cmake
  - credstash
  - ddrescue
  - dos2unix
  - emacs
  - enscript
  - ent
  - fdupes
  - ffmpeg
  - figlet
  - fpp
  - fzf
  - ghostscript
  - glide        # go package manager
  - gnu-sed
  - gnu-tar
  - goaccess     # parse webserver logs
  - gopass       # pass in go
  - highlight    # source code formatter
  - hledger
  - htop
  - httpie
  - hub          # Gitrhub tool
  - hugo
  - id3v2
  - iftop
  - imagemagick
  - iperf
  - iperf3
  - ipmitool     # IPMI tool for colo servers
  - jq
  - ledger
  - lolcat
  - mas
  - mercurial
  - mosh
  - mp3gain
  - mp3splt
  - ncdu
  - ncftp
  - ninja
  - nmap
  - normalize
  - packer
  - pandoc       # General markup converter
  - parallel
  - pass         # gpg based password manager
  - pigz
  - pv
  - pyenv
  - rbenv
  - reattach-to-user-namespace
  - rig          # Random name/address generator
  - rkflashtool  # To flash iBasso
  - rsync
  - shellcheck
  - shntool      # WAVE audio processing
  - shyaml
  - smlnj
  - socat
  - sox
  - ssh-copy-id
  - terraform-inventory
  - terraform_landscape
  - terragrunt
  - the_silver_searcher
  - tiger-vnc
  - timidity
  - tmux
  - unison
  - unrar
  - upx
  - watch
  - wget
  - wireshark  
  - wrk          # http server benchmarks
  - xmlstarlet   # xml processing

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - "0xed"
  - aerial
  - alfred
  - boxcryptor
  - calibre
  - chromedriver
  - cyberduck
  - deezer
  - djview
  - docker
  - emacs
  - filebot
  - firefox
  - goland
  - google-chrome
  - google-cloud-sdk
  - googleappengine
  - iterm2
  - keybase
  - kdiff3
  - limechat
  - minikube
  - omnigraffle
  - osxfuse
  - pycharm
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  - qlvideo
  - quicklook-json
  - quicklookase
  - r-app
  - resilio-sync
  - rstudio
  - simplenote
  - skitch
  - skype
  - suspicious-package
  - tableplus
  - teamviewer
  - tunnelblick
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio
  - visual-studio-code
  - vlc
  - vnc-viewer
  - webpquicklook
  - wireshark
  - xquartz
  - yandex-disk

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: "409183694", name: "Keynote"}
  - { id: "405399194", name: "Kindle"}
  - { id: "565098519", name: "Durak"}
  - { id: "747648890", name: "Telegram"}
  - { id: "425955336", name: "Skitch"}
  - { id: "425424353", name: "The Unarchiver"}
  - { id: "443987910", name: "1Password"}
  - { id: "682658836", name: "GarageBand"}
  - { id: "404246493", name: "MoneyWell"}
  - { id: "409203825", name: "Numbers"}
  - { id: "497799835", name: "Xcode"}
  - { id: "1153157709", name: "Speedtest"}
  - { id: "409201541", name: "Pages"}
  - { id: "408981434", name: "iMovie"}
  - { id: "406825478", name: "Telephone"}
  - { id: "715768417", name: "Microsoft Remote Desktop"}
  - { id: "1178295426", name: "Colibri"}

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
